// srvpro cube integration E2E test (dev_docs/08 M2 DoD).
// Usage: node cube-e2e.js [host] [gamePort] [httpPort] [apiKey]
// Card codes come from /tmp/cube-cardcodes.json (generated by run-e2e.sh from cards.cdb).
const net = require('net');
const http = require('http');
const fs = require('fs');

const SRVPRO_HOST = process.argv[2] || '127.0.0.1';
const SRVPRO_PORT = parseInt(process.argv[3] || '7911', 10);
const HTTP_PORT = parseInt(process.argv[4] || '7922', 10);
const API_KEY = process.argv[5] || 'cube-test-key';
const VERSION = 4962; // must match srvpro settings.version (PRO_VERSION 0x1362)
const TEST_TID = Date.now();
let roomSequence = 0;
function controllerRoom(label) {
  roomSequence += 1;
  // CTOS_JoinGame pass[20] permits 19 visible UTF-16 code units. Include the
  // label in the digest input, but keep the wire room name compact.
  const key = require('crypto').createHash('sha256')
    .update(`${TEST_TID}:${roomSequence}:${label}`)
    .digest('hex')
    .slice(0, 14);
  return `CUBE-${key}`;
}

const { main, extra } = JSON.parse(fs.readFileSync('/tmp/cube-cardcodes.json', 'utf8'));

// ---- protocol helpers (framing: [len u16][type u8][payload]) ----
function pkt(type, payload) {
  const buf = Buffer.alloc(1 + payload.length);
  buf.writeUInt8(type, 0);
  payload.copy(buf, 1);
  const out = Buffer.alloc(2 + buf.length);
  out.writeUInt16LE(buf.length, 0);
  buf.copy(out, 2);
  return out;
}
function playerInfo(name) {
  const payload = Buffer.alloc(40); // uint16_t name[20]
  payload.write(name, 0, 'utf16le');
  return pkt(0x10, payload);
}
function joinGame(roomName) {
  const payload = Buffer.alloc(48); // version u16 + pad + gameid u32 + pass u16[20]
  payload.writeUInt16LE(VERSION, 0);
  payload.writeUInt32LE(0, 4);
  payload.write(roomName, 8, 'utf16le');
  return pkt(0x12, payload);
}
function updateDeck(mainCodes, sideCodes) {
  const payload = Buffer.alloc(8 + 4 * (mainCodes.length + sideCodes.length));
  payload.writeUInt32LE(mainCodes.length, 0);
  payload.writeUInt32LE(sideCodes.length, 4);
  let off = 8;
  for (const c of mainCodes.concat(sideCodes)) { payload.writeUInt32LE(c, off); off += 4; }
  return pkt(0x2, payload);
}
const READY = pkt(0x22, Buffer.alloc(0)); // CTOS_HS_READY

// ---- srvpro cube HTTP API ----
function api(method, path, body) {
  return new Promise((resolve, reject) => {
    const req = http.request({ host: SRVPRO_HOST, port: HTTP_PORT, path, method,
      headers: { 'X-Cube-Api-Key': API_KEY, 'Content-Type': 'application/json' } }, (res) => {
      let d = '';
      res.on('data', (c) => (d += c));
      res.on('end', () => {
        try { resolve(JSON.parse(d)); } catch (e) { reject(new Error('bad json: ' + d)); }
      });
    });
    req.on('error', reject);
    if (body) req.write(JSON.stringify(body));
    req.end();
  });
}

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// A successful close must terminate the per-room host, not only remove the
// room from srvpro's registry.  Probe the host listener directly because the
// HTTP room_status endpoint cannot observe an orphaned child process.
async function waitPortClosed(port, timeoutMs = 5000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const result = await new Promise((resolve) => {
      const sock = net.connect(port, SRVPRO_HOST);
      let settled = false;
      const finish = (value) => {
        if (settled) return;
        settled = true;
        sock.destroy();
        resolve(value);
      };
      sock.once('connect', () => finish('open'));
      sock.once('error', (err) => finish(err.code === 'ECONNREFUSED' ? 'closed' : 'error'));
      sock.setTimeout(500, () => finish('timeout'));
    });
    if (result === 'closed') return true;
    await wait(100);
  }
  return false;
}

// ---- one player session: join room, upload deck (client-side), ready ----
function play(nameVpass, roomName, deck, timeoutMs = 3000) {
  return new Promise((resolve, reject) => {
    const sock = net.connect(SRVPRO_PORT, SRVPRO_HOST);
    const events = [];
    let buf = Buffer.alloc(0);
    let settled = false;
    let readySent = false;
    let completionTimer = null;
    const finish = () => {
      if (settled) return;
      settled = true;
      if (completionTimer) clearTimeout(completionTimer);
      sock.destroy();
      resolve(events);
    };
    const fail = (e) => {
      if (settled) return;
      settled = true;
      if (completionTimer) clearTimeout(completionTimer);
      sock.destroy();
      reject(e);
    };
    sock.on('error', fail);
    sock.on('data', (chunk) => {
      buf = Buffer.concat([buf, chunk]);
      while (buf.length >= 3) {
        const len = buf.readUInt16LE(0);
        if (buf.length < 2 + len) break;
        const type = buf.readUInt8(2);
        const event = { type, body: buf.slice(3, 2 + len) };
        events.push(event);
        buf = buf.slice(2 + len);
        if (readySent && type === 0x21 && [0x9, 0xa].includes(event.body.readUInt8(0) & 0xf)) {
          // Rejections send ERROR_MSG immediately after HS_PLAYER_CHANGE; leave
          // a short drain window so diagnostics retain both packets.
          setTimeout(finish, 50);
        }
      }
    });
    (async () => {
      await new Promise((r) => sock.once('connect', r));
      sock.write(playerInfo(nameVpass));
      await wait(100);
      sock.write(joinGame(roomName));
      await wait(300);
      sock.write(updateDeck(deck.main, deck.side));
      await wait(100);
      readySent = true;
      sock.write(READY);
      completionTimer = setTimeout(finish, timeoutMs);
    })().catch(fail);
  });
}

function hsStatus(events) {
  const hs = events.find((e) => e.type === 0x21); // STOC_HS_PLAYER_CHANGE
  if (!hs) return null;
  return hs.body.readUInt8(0) & 0xf;
}
function errorMsg(events) {
  const em = events.find((e) => e.type === 0x2); // STOC_ERROR_MSG
  if (!em) return null;
  return { msg: em.body.readUInt8(0), code: (em.body.readUInt32LE(4) >>> 0).toString(16) };
}
function dumpEvents(events) {
  return events.map((e) => {
    if (e.type === 0x21) return `HS_CHANGE(status=${hsStatus(events)})`;
    if (e.type === 0x2) return `ERROR_MSG(${JSON.stringify(errorMsg(events))})`;
    return `type=0x${e.type.toString(16)}`;
  });
}

const validMain = main.slice(0, 40);
// Keep the client-side upload probe valid against every cards.cdb revision.
// The old fixture used 8964, which was removed from recent upstream CDBs and
// caused unrelated deck-override checks to fail with an UNKNOWNCARD error.
const clientGarbageCode = main[0] || 1;
const deck39 = { main: main.slice(0, 39), side: [] };
const deckTruncated = { main: main.slice(0, 55), side: [] };
const deckUnknown = { main: validMain.slice(0, 39).concat([99999999]), side: [] };

function baseRoom(name, decks) {
  const players = ['alice', 'bob'];
  const normalizedDecks = {};
  for (const playerId of players) {
    const source = decks[playerId] || { main: validMain, side: [] };
    normalizedDecks[playerId] = {
      main: source.main,
      side: source.side,
      filename: `cube-deck-e2e-${playerId}-${TEST_TID}`,
    };
  }
  return {
    room_name: name,
    request_id: `e2e:${name}`,
    hostinfo: { mode: 1, rule: 5, lflist: -1, duel_rule: 3, start_lp: 8000, start_hand: 5, draw_count: 1, time_limit: 180 },
    deck_size: { main_min: 40, main_max: 50, extra_max: 10, side_max: 5 },
    players: players.map((playerId) => ({ player_id: playerId, name_vpass: playerId })),
    cube_decks: normalizedDecks,
  };
}

(async () => {
  let pass = 0, fail = 0;
  const check = (name, cond, detail) => {
    if (cond) { pass++; console.log(`PASS ${name}`); }
    else { fail++; console.log(`FAIL ${name}: ${detail}`); }
  };

  // 1. valid recorded deck; client uploads garbage -> overridden, ready accepted
  const room1Name = controllerRoom('valid');
  let room = baseRoom(room1Name, { alice: { main: validMain, side: extra.slice(0, 5) } });
  let r = await api('POST', '/cube/create_room', room);
  check('R1 create', r.ok === true, JSON.stringify(r));
  const retry = await api('POST', '/cube/create_room', room);
  check('R1 idempotent retry reuses host', retry.ok === true && retry.port === r.port, JSON.stringify(retry));
  const conflict = await api('POST', '/cube/create_room', { ...room, deck_size: { ...room.deck_size, main_max: 51 } });
  check('R1 conflicting retry rejected', conflict.ok === false && conflict.code === 'ROOM_CONFLICT', JSON.stringify(conflict));
  const ev1 = await play('alice', room1Name, { main: [clientGarbageCode, clientGarbageCode, clientGarbageCode], side: [] });
  check('R1 ready accepted (deck overridden)', hsStatus(ev1) === 0x9, JSON.stringify(dumpEvents(ev1)));
  await api('POST', '/cube/close_room', { room_name: room1Name });

  // 2. recorded deck 39 main (< main_min 40) -> rejected even with no_check_deck=T
  const room2Name = controllerRoom('short');
  room = baseRoom(room2Name, { alice: { main: deck39.main, side: [] } });
  r = await api('POST', '/cube/create_room', room);
  check('R2 create', r.ok === true, JSON.stringify(r));
  const ev2 = await play('alice', room2Name, { main: [clientGarbageCode], side: [] });
  check('R2 rejected (MAINCOUNT)', hsStatus(ev2) === 0xa, JSON.stringify(dumpEvents(ev2)));
  await api('POST', '/cube/close_room', { room_name: room2Name });

  // 3. recorded deck 55 main -> truncated to main_max=50 and accepted (runtime upper limit)
  const room3Name = controllerRoom('truncate');
  room = baseRoom(room3Name, { alice: { main: deckTruncated.main, side: [] } });
  r = await api('POST', '/cube/create_room', room);
  check('R3 create', r.ok === true, JSON.stringify(r));
  const ev3 = await play('alice', room3Name, { main: [clientGarbageCode], side: [] });
  check('R3 accepted (truncated to 50)', hsStatus(ev3) === 0x9, JSON.stringify(dumpEvents(ev3)));
  await api('POST', '/cube/close_room', { room_name: room3Name });

  // 4. recorded deck contains unknown card id -> rejected (ID validation)
  const room4Name = controllerRoom('unknown');
  room = baseRoom(room4Name, { alice: { main: deckUnknown.main, side: [] } });
  r = await api('POST', '/cube/create_room', room);
  check('R4 create', r.ok === true, JSON.stringify(r));
  const ev4 = await play('alice', room4Name, { main: [clientGarbageCode], side: [] });
  check('R4 rejected (UNKNOWNCARD)', hsStatus(ev4) === 0xa, JSON.stringify(dumpEvents(ev4)));
  await api('POST', '/cube/close_room', { room_name: room4Name });

  // 5. API auth: no key -> 401
  const noKey = await new Promise((resolve) => {
    const req = http.request({ host: SRVPRO_HOST, port: HTTP_PORT, path: '/cube/create_room', method: 'POST' }, (res) => {
      let d = ''; res.on('data', (c) => (d += c)); res.on('end', () => resolve({ status: res.statusCode, body: d }));
    });
    req.on('error', () => resolve({ status: 0 }));
    req.end();
  });
  check('R5 401 without api key', noKey.status === 401, JSON.stringify(noKey));

  // 6. Controller payloads larger than the configured zones are rejected
  // before spawn; ordinary rule-string rooms below still exercise host truncation.
  room = baseRoom(controllerRoom('oversize'), { alice: { main: validMain.concat(extra), side: main.slice(40, 48) } });
  r = await api('POST', '/cube/create_room', room);
  check('R6 oversized controller deck rejected before spawn', r.ok === false && r.code === 'BAD_PAYLOAD', JSON.stringify(r));

  // 7. close an idle room before any player connects; this is the regression
  // that previously left an orphaned ygopro host listening on its port.
  const closeProbeName = controllerRoom('closeprobe');
  const closeProbe = await api('POST', '/cube/create_room', baseRoom(closeProbeName, {
    alice: { main: validMain, side: extra.slice(0, 5) },
  }));
  check('R7 close probe create', closeProbe.ok === true, JSON.stringify(closeProbe));
  await api('POST', '/cube/close_room', { room_name: closeProbeName });
  const closeProbeStopped = closeProbe.ok && await waitPortClosed(closeProbe.port);
  check('R7 close stops idle host', closeProbeStopped, `port ${closeProbe.port} still accepts connections`);

  // 8. legacy rule-string tokens (room passwords are limited to 20 chars, so tokens
  //    are split across rooms): MAIN35-45 -> 37 main accepted (below default 40),
  //    34 rejected; EXTRA3,SIDE2 -> 5 extra / 6 side truncated to 3/2, accepted
  const sfx = () => Math.random().toString(36).slice(-2);
  const ev7a = await play('carol$pw3', `MAIN35-45#${sfx()}`, { main: main.slice(0, 37), side: [] });
  check('R7 token path: 37 main accepted (MAIN35-45)', hsStatus(ev7a) === 0x9, JSON.stringify(dumpEvents(ev7a)));
  const ev7b = await play('carol$pw3', `MAIN35-45#${sfx()}`, { main: main.slice(0, 34), side: [] });
  check('R7 token path: 34 main rejected (<35)', hsStatus(ev7b) === 0xa, JSON.stringify(dumpEvents(ev7b)));
  const ev7c = await play('carol$pw3', `EXTRA3,SIDE2#${sfx()}`, { main: main.slice(0, 40).concat(extra.slice(0, 5)), side: main.slice(40, 46) });
  check('R7 token path: extra 5->3, side 6->2 truncated', hsStatus(ev7c) === 0x9, JSON.stringify(dumpEvents(ev7c)));

  // 9. CUBE is the compact match profile: M, TM999, EX30 and SD30.  Use
  // distinct cards so the regular deck legality check does not mask the
  // runtime extra/side limit assertion.
  const cubeDeck = {
    main: main.slice(0, 40).concat(extra.slice(0, 31)),
    side: main.slice(40, 71),
  };
  const evCube = await play('carol$pw3', `CUBE#${sfx()}`, cubeDeck);
  check('R9 CUBE shorthand: extra 31->30, side 31->30 truncated', hsStatus(evCube) === 0x9, JSON.stringify(dumpEvents(evCube)));

  // 10. regression: no deck_size tokens + NC -> no forced check (39 main accepted);
  //    NC + MAIN token -> deck_limits_set forces the check (39 rejected)
  const ev8a = await play('dave$pw4', `NC#${sfx()}`, { main: main.slice(0, 39), side: [] });
  check('R10 regression: NC without tokens -> 39 main accepted', hsStatus(ev8a) === 0x9, JSON.stringify(dumpEvents(ev8a)));
  const ev8b = await play('dave$pw4', `NC,MAIN40-50#${sfx()}`, { main: main.slice(0, 39), side: [] });
  check('R10 regression: NC + MAIN40-50 -> 39 main rejected', hsStatus(ev8b) === 0xa, JSON.stringify(dumpEvents(ev8b)));

  console.log(`\n== ${pass} passed, ${fail} failed ==`);
  process.exit(fail ? 1 : 0);
})().catch((e) => { console.error('E2E ERROR', e); process.exit(2); });
