#!/usr/bin/env python3
"""Generate the allowlist from pinned upstream bot.conf, executors and Dialogs."""
import pathlib, re, shlex, json, sys
root, output = map(pathlib.Path, sys.argv[1:3])
executors = {}
for path in sorted((root/'Game/AI/Decks').glob('*.cs')):
    for name, file in re.findall(r'\[Deck\("([^"]+)",\s*"([^"]+)"', path.read_text(encoding='utf-8-sig')):
        executors[name] = file
entries = {}
lines = (root/'BotWrapper/bot.conf').read_text(encoding='utf-8-sig').splitlines()
for i, line in enumerate(lines):
    if not line.startswith('!'): continue
    args = dict(p.split('=',1) for p in shlex.split(lines[i+1]) if '=' in p)
    if 'Deck' not in args or 'SELECT_DECKFILE' in lines[i+3]: continue
    deck = args['Deck']; assert deck in executors
    assert (root/'Dialogs'/(args.get('Dialog','default')+'.json')).is_file()
    name = args.get('Name','WindBot'); title = line[1:]
    title = title[len(name)+1:] if title.startswith(name+'-') else lines[i+2].removesuffix('卡组。').removesuffix('。')
    if deck in ['MokeyMokey', 'MokeyMokeyKing']: title = name
    entries[deck] = dict(id=deck, name=title, description=lines[i+2], robot=name, dialog=args.get('Dialog','default'), deckFile=executors[deck])
labels = {'Blackwing':'黑羽','CyberDragon':'电子龙','Evilswarm':'入魔','Gravekeeper':'守墓','Graydle':'灰篮','MathMech':'斩机','Nekroz':'影灵衣','OldSchool':'复古卡组','Voiceless':'肃声'}
excluded = []
for deck, file in executors.items():
    if not (root/'Decks'/(file+'.ydk')).is_file():
        assert deck not in entries; excluded.append(deck); continue
    if deck not in entries:
        entries[deck] = dict(id=deck,name=labels.get(deck,deck),description='上游附带卡组',robot='默认机器人',dialog='zh-CN',deckFile=file)
values = list(entries.values())
output.write_text('// Generated by scripts/windbot/generate-catalog.py; upstream 7acd93d.\nimport type { DuelBot } from "@ygocube/shared";\nexport const BOT_CATALOG: (DuelBot & { dialog: string; deckFile: string })[] = '+json.dumps(values,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(json.dumps(dict(robots=len(set(v['robot'] for v in values)),decks=len(values),withoutBundledDeck=excluded),ensure_ascii=False))
