// Generated by scripts/windbot/generate-catalog.py; upstream 7acd93d.
import type { DuelBot } from "@ygocube/shared";
export const BOT_CATALOG: (DuelBot & { dialog: string; deckFile: string })[] = [
  {
    "id": "MokeyMokey",
    "name": "悠悠",
    "description": "沙包。",
    "robot": "悠悠",
    "dialog": "mokey.zh-CN",
    "deckFile": "AI_MokeyMokey"
  },
  {
    "id": "MokeyMokeyKing",
    "name": "悠悠王",
    "description": "大沙包。",
    "robot": "悠悠王",
    "dialog": "mokey.zh-CN",
    "deckFile": "AI_MokeyMokeyKing"
  },
  {
    "id": "Dragunity",
    "name": "龙骑星爆",
    "description": "龙骑轴星尘龙爆裂体卡组。",
    "robot": "谜之剑士LV4",
    "dialog": "swordsman.zh-CN",
    "deckFile": "AI_Dragunity"
  },
  {
    "id": "Level VIII",
    "name": "L8",
    "description": "8星同调卡组。",
    "robot": "谜之剑士LV4",
    "dialog": "swordsman.zh-CN",
    "deckFile": "AI_Level8"
  },
  {
    "id": "Rank V",
    "name": "R5",
    "description": "5阶超量卡组。",
    "robot": "谜之剑士LV4",
    "dialog": "swordsman.zh-CN",
    "deckFile": "AI_Rank5"
  },
  {
    "id": "Zexal Weapons",
    "name": "异热同心武器",
    "description": "神装电光皇卡组。",
    "robot": "谜之剑士LV4",
    "dialog": "swordsman.zh-CN",
    "deckFile": "AI_ZexalWeapons"
  },
  {
    "id": "HeroBeat1103",
    "name": "1103英雄",
    "description": "2011年3月的英雄卡组。",
    "robot": "谜之剑士LV4",
    "dialog": "swordsman.zh-CN",
    "deckFile": "AI_HeroBeat1103"
  },
  {
    "id": "Rainbow",
    "name": "彩虹",
    "description": "全属性凡骨卡组。",
    "robot": "琪露诺",
    "dialog": "cirno.zh-CN",
    "deckFile": "AI_Rainbow"
  },
  {
    "id": "Toadally Awesome",
    "name": "饼蛙",
    "description": "大师规则三的全盛饼蛙卡组。",
    "robot": "琪露诺",
    "dialog": "cirno.zh-CN",
    "deckFile": "AI_ToadallyAwesome"
  },
  {
    "id": "Blue-Eyes",
    "name": "青眼",
    "description": "青眼卡组。",
    "robot": "复制植物",
    "dialog": "copy.zh-CN",
    "deckFile": "AI_BlueEyes"
  },
  {
    "id": "Zoodiac",
    "name": "十二兽",
    "description": "大师规则三的十四兽卡组。",
    "robot": "复制植物",
    "dialog": "copy.zh-CN",
    "deckFile": "AI_Zoodiac"
  },
  {
    "id": "Rank8",
    "name": "R8",
    "description": "8阶超量卡组。",
    "robot": "复制植物",
    "dialog": "copy.zh-CN",
    "deckFile": "AI_Rank8"
  },
  {
    "id": "Lightsworn",
    "name": "光道",
    "description": "旧式光道卡组。",
    "robot": "复制植物",
    "dialog": "copy.zh-CN",
    "deckFile": "AI_Lightsworn"
  },
  {
    "id": "Yosenju",
    "name": "妖仙兽",
    "description": "妖仙兽卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Yosenju"
  },
  {
    "id": "Qliphort",
    "name": "机壳",
    "description": "机壳卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Qliphort"
  },
  {
    "id": "Trickstar",
    "name": "淘气仙星",
    "description": "旧式淘气仙星卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Trickstar"
  },
  {
    "id": "Altergeist",
    "name": "幻变骚灵",
    "description": "幻变骚灵卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Altergeist"
  },
  {
    "id": "Labrynth",
    "name": "拉比林斯迷宫",
    "description": "拉比林斯迷宫卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Labrynth"
  },
  {
    "id": "Yubel",
    "name": "于贝尔",
    "description": "于贝尔卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Yubel"
  },
  {
    "id": "Apophis",
    "name": "王家的神殿",
    "description": "王家的神殿卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Apophis"
  },
  {
    "id": "Archfiend",
    "name": "恶魔",
    "description": "恶魔卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Archfiend"
  },
  {
    "id": "Enneacraft",
    "name": "纠罪巧",
    "description": "纠罪巧卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Enneacraft"
  },
  {
    "id": "Pumpking",
    "name": "南瓜王",
    "description": "不死族卡组。",
    "robot": "尼亚",
    "dialog": "near.zh-CN",
    "deckFile": "AI_Pumpking"
  },
  {
    "id": "SkyStriker",
    "name": "闪刀姬",
    "description": "旧式闪刀姬卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_SkyStriker"
  },
  {
    "id": "Orcust",
    "name": "自奏圣乐",
    "description": "旧式自奏圣乐卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_Orcust"
  },
  {
    "id": "Salamangreat",
    "name": "转生炎兽",
    "description": "转生炎兽卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_Salamangreat"
  },
  {
    "id": "Ryzeal",
    "name": "雷火沸动",
    "description": "初代雷火沸动卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_Ryzeal"
  },
  {
    "id": "Maliss",
    "name": "码丽丝",
    "description": "MD全盛码丽丝卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_Maliss"
  },
  {
    "id": "BE2025",
    "name": "青眼",
    "description": "2025年的青眼卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_BE2025"
  },
  {
    "id": "SacredBeast",
    "name": "三幻魔",
    "description": "三幻魔卡组。",
    "robot": "复制梁龙",
    "dialog": "anothercopy.zh-CN",
    "deckFile": "AI_SacredBeast"
  },
  {
    "id": "FamiliarPossessed",
    "name": "凭依装着",
    "description": "凭依装着卡组。",
    "robot": "VI-1911",
    "dialog": "VI-1911.zh-CN",
    "deckFile": "AI_FamiliarPossessed"
  },
  {
    "id": "TimeThief",
    "name": "时劫者",
    "description": "时间潜行者卡组。",
    "robot": "VI-1911",
    "dialog": "VI-1911.zh-CN",
    "deckFile": "AI_Timethief"
  },
  {
    "id": "Burn",
    "name": "削血",
    "description": "老式削血卡组。",
    "robot": "永远之魂",
    "dialog": "soul.zh-CN",
    "deckFile": "AI_Burn"
  },
  {
    "id": "Frog",
    "name": "青蛙",
    "description": "老式青蛙卡组。",
    "robot": "永远之魂",
    "dialog": "soul.zh-CN",
    "deckFile": "AI_Frog"
  },
  {
    "id": "Horus",
    "name": "荷鲁斯",
    "description": "老式龙族卡组。",
    "robot": "永远之魂",
    "dialog": "soul.zh-CN",
    "deckFile": "AI_Horus"
  },
  {
    "id": "Chaos408",
    "name": "408混沌",
    "description": "408环境混沌卡组。",
    "robot": "永远之魂",
    "dialog": "soul.zh-CN",
    "deckFile": "AI_Chaos408"
  },
  {
    "id": "Monarch506",
    "name": "506风帝",
    "description": "506环境风帝卡组。建议使用原版效果补丁以使洗脑和圆盘人等卡能够以506环境的效果正常运行。",
    "robot": "永远之魂",
    "dialog": "soul.zh-CN",
    "deckFile": "AI_Monarch506"
  },
  {
    "id": "PureWinds",
    "name": "微风",
    "description": "风属性卡组。",
    "robot": "比特机灵",
    "dialog": "zh-CN",
    "deckFile": "AI_PureWinds"
  },
  {
    "id": "ST1732",
    "name": "由三盒ST17和三盒SD32组成的",
    "description": "由三盒ST17和三盒SD32组成的卡组。",
    "robot": "试作型机器人1732",
    "dialog": "zh-CN",
    "deckFile": "AI_ST1732"
  },
  {
    "id": "LightswornShaddoldinosour",
    "name": "光道影依恐龙",
    "description": "光道影依恐龙卡组。",
    "robot": "奇異果",
    "dialog": "kiwi.zh-TW",
    "deckFile": "AI_LightswornShaddoldinosour"
  },
  {
    "id": "DarkMagician",
    "name": "黑魔术师",
    "description": "黑魔术师卡组。",
    "robot": "奇魔果",
    "dialog": "kiwi.zh-TW",
    "deckFile": "AI_DarkMagician"
  },
  {
    "id": "BlueEyesMaxDragon",
    "name": "青眼混沌极龙",
    "description": "青眼混沌极龙卡组。",
    "robot": "MAX龍果",
    "dialog": "kiwi.zh-TW",
    "deckFile": "AI_BlueEyesMaxDragon"
  },
  {
    "id": "Phantasm",
    "name": "幻煌龙",
    "description": "幻煌龙卡组。",
    "robot": "幻煌果",
    "dialog": "kiwi.zh-TW",
    "deckFile": "AI_Phantasm"
  },
  {
    "id": "ChainBurn",
    "name": "连锁烧",
    "description": "连锁烧卡组。",
    "robot": "燃血鬥士",
    "dialog": "kiwi.zh-TW",
    "deckFile": "AI_ChainBurn"
  },
  {
    "id": "GrenMajuThunderBoarder",
    "name": "红莲雷王滑板",
    "description": "红莲雷王滑板卡组。",
    "robot": "報社鬥士",
    "dialog": "kiwi.zh-TW",
    "deckFile": "AI_GrenMajuThunderBoarder"
  },
  {
    "id": "Dragun",
    "name": "真红眼龙骑士",
    "description": "超魔导真红眼龙骑士卡组。",
    "robot": "我太帅了",
    "dialog": "smart.zh-CN",
    "deckFile": "AI_Dragun"
  },
  {
    "id": "Brave",
    "name": "水百凤凰勇者",
    "description": "水机百头龙凤凰人勇者卡组。",
    "robot": "我太帅了",
    "dialog": "smart.zh-CN",
    "deckFile": "AI_Brave"
  },
  {
    "id": "Witchcraft",
    "name": "魔女术",
    "description": "魔女术卡组。",
    "robot": "玻璃女巫",
    "dialog": "verre.zh-CN",
    "deckFile": "AI_Witchcraft"
  },
  {
    "id": "Exosister",
    "name": "救祓少女",
    "description": "救祓少女卡组。",
    "robot": "玻璃女巫",
    "dialog": "verre.zh-CN",
    "deckFile": "AI_Exosister"
  },
  {
    "id": "Swordsoul",
    "name": "相剑",
    "description": "相剑卡组。",
    "robot": "艾克莉西娅",
    "dialog": "ecclesia.zh-CN",
    "deckFile": "AI_Swordsoul"
  },
  {
    "id": "Dogmatika",
    "name": "教导",
    "description": "教导卡组。",
    "robot": "艾克莉西娅",
    "dialog": "ecclesia.zh-CN",
    "deckFile": "AI_Dogmatika"
  },
  {
    "id": "Albaz",
    "name": "阿不思",
    "description": "以阿不思的落胤为中心的卡组。",
    "robot": "艾克莉西娅",
    "dialog": "ecclesia.zh-CN",
    "deckFile": "AI_Albaz"
  },
  {
    "id": "Kashtira",
    "name": "刹帝利",
    "description": "俱舍怒威族卡组。",
    "robot": "神数不神",
    "dialog": "Zefra.zh-CN",
    "deckFile": "AI_Kashtira"
  },
  {
    "id": "ThunderDragon",
    "name": "雷龙",
    "description": "深渊混沌雷龙卡组。不符合禁限卡表。",
    "robot": "神数不神",
    "dialog": "Zefra.zh-CN",
    "deckFile": "AI_ThunderDragon"
  },
  {
    "id": "Tearlaments",
    "name": "珠泪哀歌",
    "description": "旧式地天使珠泪哀歌族卡组。",
    "robot": "神数不神",
    "dialog": "Zefra.zh-CN",
    "deckFile": "AI_Tearlaments"
  },
  {
    "id": "Zefra",
    "name": "神数",
    "description": "神数卡组。",
    "robot": "神数不神",
    "dialog": "Zefra.zh-CN",
    "deckFile": "AI_Zefra"
  },
  {
    "id": "SuperheavySamurai",
    "name": "超重武者",
    "description": "超重武者卡组。",
    "robot": "今晚有宵夜吗",
    "dialog": "superheavysamurai.zh-CN",
    "deckFile": "AI_SuperheavySamurai"
  },
  {
    "id": "MalissOCG",
    "name": "码丽丝",
    "description": "码丽丝卡组。",
    "robot": "今晚有宵夜吗",
    "dialog": "Xiaoye.zh-CN",
    "deckFile": "AI_MalissOCG"
  },
  {
    "id": "Neko",
    "name": "味美喵",
    "description": "他似乎不会玩味美喵。",
    "robot": "今晚有宵夜吗",
    "dialog": "Xiaoye.zh-CN",
    "deckFile": "AI_Neko"
  },
  {
    "id": "RadiantTyphoon",
    "name": "絢嵐",
    "description": "絢嵐卡組。",
    "robot": "偷摸灵兽幽灵",
    "dialog": "soyorin.zh-TW",
    "deckFile": "AI_RadiantTyphoon"
  },
  {
    "id": "ChaosRitual",
    "name": "光與闇的儀式",
    "description": "光與闇的儀式卡組。",
    "robot": "偷摸灵兽幽灵",
    "dialog": "soyorin.zh-TW",
    "deckFile": "AI_ChaosRitual"
  },
  {
    "id": "Blackwing",
    "name": "黑羽",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Blackwing"
  },
  {
    "id": "CyberDragon",
    "name": "电子龙",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_CyberDragon"
  },
  {
    "id": "Evilswarm",
    "name": "入魔",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Evilswarm"
  },
  {
    "id": "Gravekeeper",
    "name": "守墓",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Gravekeeper"
  },
  {
    "id": "Graydle",
    "name": "灰篮",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Graydle"
  },
  {
    "id": "MathMech",
    "name": "斩机",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Mathmech"
  },
  {
    "id": "Nekroz",
    "name": "影灵衣",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Nekroz"
  },
  {
    "id": "OldSchool",
    "name": "复古卡组",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_OldSchool"
  },
  {
    "id": "Voiceless",
    "name": "肃声",
    "description": "上游附带卡组",
    "robot": "默认机器人",
    "dialog": "zh-CN",
    "deckFile": "AI_Voiceless"
  }
];
