export const duelText = {
  zh: {
    command: "动作",
    yesno: "确认",
    cards: "卡片",
    place: "场地区域",
    tribute: "祭品",
    sum: "数值合计",
    sort: "排序",
    unselect: "选择 / 取消",
    mask: "宣言",
    declare: "卡名宣言",
    title: "网页对战",
    watch: "观战",
    replay: "对战录像",
    connect: "连接中…",
    connected: "已连接",
    reconnect: "重新连接",
    ready: "准备",
    unready: "取消准备",
    start: "开始对战",
    surrender: "投降",
    confirmSurrender: "确认投降本局？",
    yes: "是",
    no: "否",
    confirm: "确认",
    cancel: "取消 / 完成",
    waiting: "等待对方操作",
    details: "卡片详情",
    close: "关闭",
    unknown: "未知卡",
    summon: "通常召唤",
    special: "特殊召唤",
    position: "改变表示",
    setMonster: "盖放怪兽",
    setSpell: "盖放",
    activate: "发动效果",
    attack: "攻击",
    battle: "战斗阶段",
    main2: "主要阶段 2",
    end: "结束阶段",
    shuffle: "洗切手牌",
    position1: "表侧攻击",
    position2: "里侧攻击",
    position4: "表侧守备",
    position8: "里侧守备",
    hand1: "剪刀",
    hand2: "石头",
    hand3: "布",
    first: "先攻",
    second: "后攻",
    siding: "局间换备",
    submitSide: "提交换备",
    side: "备选卡组",
    main: "主卡组",
    extra: "额外卡组",
    select: "选择",
    selected: "已选",
    required: "必选",
    chain: "连锁",
    log: "对战记录",
    play: "播放",
    pause: "暂停",
    step: "单步",
    incomplete: "录像不完整",
    replayLocked: "整场比赛结束后才能观看录像",
    back: "返回比赛",
    search: "输入卡名或编号",
    retry: "宿主拒绝了选择，请重新选择",
    always: "每次询问",
    skip: "跳过可选连锁",
    auto: "无可用连锁时跳过",
    material: "素材",
    counter: "指示物",
    language: "EN",
    error: "连接或协议错误",
    caughtUp: "同步场面中…",
    accept: "已提交",
    takeover: "连接已被另一个窗口接管",
    zones: ["牌库", "手牌", "怪兽区", "魔法陷阱区", "墓地", "除外", "额外卡组"],
    phases: [
      "抽卡",
      "准备",
      "主要 1",
      "战斗开始",
      "战斗",
      "伤害",
      "伤害计算",
      "战斗结束",
      "主要 2",
      "结束",
    ],
  },
  en: {
    command: "Action",
    yesno: "Confirmation",
    cards: "Cards",
    place: "Zone",
    tribute: "Tributes",
    sum: "Sum",
    sort: "Order",
    unselect: "Select / Unselect",
    mask: "Declaration",
    declare: "Declare a card",
    title: "Web duel",
    watch: "Public spectator",
    replay: "Omniscient replay",
    connect: "Connecting…",
    connected: "Connected",
    reconnect: "Reconnect",
    ready: "Ready",
    unready: "Not ready",
    start: "Start duel",
    surrender: "Surrender",
    confirmSurrender: "Surrender this game?",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    cancel: "Cancel / Finish",
    waiting: "Waiting for opponent",
    details: "Card details",
    close: "Close",
    unknown: "Unknown card",
    summon: "Normal summon",
    special: "Special summon",
    position: "Change position",
    setMonster: "Set monster",
    setSpell: "Set",
    activate: "Activate effect",
    attack: "Attack",
    battle: "Battle phase",
    main2: "Main phase 2",
    end: "End phase",
    shuffle: "Shuffle hand",
    position1: "Face-up attack",
    position2: "Face-down attack",
    position4: "Face-up defense",
    position8: "Face-down defense",
    hand1: "Scissors",
    hand2: "Rock",
    hand3: "Paper",
    first: "First",
    second: "Second",
    siding: "Side decking",
    submitSide: "Submit side deck",
    side: "Side deck",
    main: "Main deck",
    extra: "Extra deck",
    select: "Select",
    selected: "Selected",
    required: "Required",
    chain: "Chain",
    log: "Duel log",
    play: "Play",
    pause: "Pause",
    step: "Step",
    incomplete: "Incomplete recording",
    replayLocked: "Replays open when the tournament finishes",
    back: "Back to matches",
    search: "Card name or code",
    retry: "The host rejected the response. Select again.",
    always: "Always ask",
    skip: "Skip optional chains",
    auto: "Skip empty chains",
    material: "Materials",
    counter: "Counters",
    language: "中文",
    error: "Connection or protocol error",
    caughtUp: "Restoring field…",
    accept: "Submitted",
    takeover: "Another window took control",
    zones: [
      "Deck",
      "Hand",
      "Monsters",
      "Spells & traps",
      "Graveyard",
      "Banished",
      "Extra deck",
    ],
    phases: [
      "Draw",
      "Standby",
      "Main 1",
      "Battle start",
      "Battle",
      "Damage",
      "Damage calculation",
      "Battle end",
      "Main 2",
      "End",
    ],
  },
};
export type DuelLanguage = keyof typeof duelText;
export const races = {
  zh: [
    "战士",
    "魔法师",
    "天使",
    "恶魔",
    "不死",
    "机械",
    "水",
    "炎",
    "岩石",
    "鸟兽",
    "植物",
    "昆虫",
    "雷",
    "龙",
    "兽",
    "兽战士",
    "恐龙",
    "鱼",
    "海龙",
    "爬虫类",
    "念动力",
    "幻神兽",
    "创造神",
    "幻龙",
    "电子界",
    "幻想魔",
  ],
  en: [
    "Warrior",
    "Spellcaster",
    "Fairy",
    "Fiend",
    "Zombie",
    "Machine",
    "Aqua",
    "Pyro",
    "Rock",
    "Winged Beast",
    "Plant",
    "Insect",
    "Thunder",
    "Dragon",
    "Beast",
    "Beast-Warrior",
    "Dinosaur",
    "Fish",
    "Sea Serpent",
    "Reptile",
    "Psychic",
    "Divine-Beast",
    "Creator God",
    "Wyrm",
    "Cyberse",
    "Illusion",
  ],
};
export const attributes = {
  zh: ["地", "水", "炎", "风", "光", "暗", "神"],
  en: ["Earth", "Water", "Fire", "Wind", "Light", "Dark", "Divine"],
};
